import {
    Activity,
    AlertTriangle,
    Box,
    Command,
    Database,
    Eye,
    FileJson,
    GamepadIcon,
    Globe,
    Heart,
    Key,
    Layout,
    List,
    Lock,
    MessageSquare,
    Network,
    Package,
    Play,
    Radio,
    Shield,
    Sword,
    Terminal,
    Timer,
    User,
    Users,
    GlobeIcon as World
} from "lucide-react";
import {PropertyMapping} from "@/types/config"

export const propertyMappings: PropertyMapping[] = [
    {name: "enable-jmx-monitoring", icon: Activity, type: "boolean"},
    {name: "level-seed", icon: World, type: "string"},
    {name: "rcon.port", icon: Terminal, type: "number"},
    {name: "enable-command-block", icon: Command, type: "boolean"},
    {
        name: "gamemode",
        icon: GamepadIcon,
        type: "gamemode",
        options: ["survival", "creative", "adventure", "spectator"]
    },
    {name: "enable-query", icon: Radio, type: "boolean"},
    {name: "generator-settings", icon: FileJson, type: "json"},
    {name: "enforce-secure-profile", icon: Shield, type: "boolean"},
    {name: "spawn-protection", icon: Shield, type: "number"},
    {name: "level-name", icon: Database, type: "string"},
    {name: "log-ips", icon: Network, type: "boolean"},
    {name: "motd", icon: MessageSquare, type: "string"},
    {name: "query.port", icon: Radio, type: "number"},
    {name: "pvp", icon: Sword, type: "boolean"},
    {name: "generate-structures", icon: Box, type: "boolean"},
    {name: "snooper-enabled", icon: Network, type: "boolean"},
    {name: "difficulty", icon: AlertTriangle, type: "difficulty", options: ["peaceful", "easy", "normal", "hard"]},
    {name: "network-compression-threshold", icon: Network, type: "number"},
    {name: "max-players", icon: Users, type: "number"},
    {
        name: "online-mode",
        icon: Lock,
        type: "boolean"
    },
    {name: "allow-flight", icon: Play, type: "boolean"},
    {name: "hide-online-players", icon: Users, type: "boolean"},
    {name: "view-distance", icon: Eye, type: "number"},
    {name: "server-port", icon: Globe, type: "number"},
    {name: "enable-rcon", icon: Terminal, type: "boolean"},
    {name: "op-permission-level", icon: Shield, type: "number"},
    {name: "pause-when-empty-seconds", icon: Timer, type: "number"},
    {name: "resource-pack", icon: Package, type: "string"},
    {name: "simulation-distance", icon: Layout, type: "number"},
    {name: "max-chained-neighbor-updates", icon: Network, type: "number"},
    {name: "player-idle-timeout", icon: Timer, type: "number"},
    {name: "rcon.password", icon: Key, type: "string"},
    {name: "max-tick-time", icon: Timer, type: "number"},
    {name: "debug", icon: Terminal, type: "boolean"},
    {name: "enforce-whitelist", icon: List, type: "boolean"},
    {name: "force-gamemode", icon: GamepadIcon, type: "boolean"},
    {name: "hardcore", icon: Heart, type: "boolean"},
    {name: "accepts-transfers", icon: Network, type: "boolean"},
    {name: "white-list", icon: List, type: "boolean"},
    {name: "spawn-npcs", icon: User, type: "boolean"},
    {name: "spawn-animals", icon: Users, type: "boolean"},
    {name: "spawn-monsters", icon: AlertTriangle, type: "boolean"},
    {name: "require-resource-pack", icon: Package, type: "boolean"},
    {name: "use-native-transport", icon: Network, type: "boolean"},
    {name: "prevent-proxy-connections", icon: Network, type: "boolean"},
    {name: "enable-status", icon: Network, type: "boolean"},
    {name: "rate-limit", icon: Network, type: "number"},
    {name: "broadcast-rcon-to-ops", icon: Network, type: "boolean"},
    {name: "broadcast-console-to-ops", icon: Network, type: "boolean"},
    {name: "allow-nether", icon: World, type: "boolean"},
    {name: "sync-chunk-writes", icon: Network, type: "boolean"}
];