import {
    ChartLineUpIcon,
    WarningIcon,
    CubeIcon,
    CommandIcon,
    DatabaseIcon,
    EyeIcon,
    FileCodeIcon,
    GameControllerIcon,
    GlobeIcon,
    HeartIcon,
    KeyIcon,
    LayoutIcon,
    ListIcon,
    LockKeyIcon,
    ChatCircleIcon,
    WifiHighIcon,
    PackageIcon,
    PlayIcon,
    BroadcastIcon,
    ShieldIcon,
    SwordIcon,
    TerminalIcon,
    TimerIcon,
    UserIcon,
    UsersIcon,
    GlobeHemisphereWestIcon
} from "@phosphor-icons/react";
import {PropertyMapping} from "@/types/config"

export const propertyMappings: PropertyMapping[] = [
    {name: "gamemode", icon: GameControllerIcon, type: "gamemode", options: ["survival", "creative", "adventure", "spectator"], category: "gameplay"},
    {name: "difficulty", icon: WarningIcon, type: "difficulty", options: ["peaceful", "easy", "normal", "hard"], category: "gameplay"},
    {name: "hardcore", icon: HeartIcon, type: "boolean", category: "gameplay"},
    {name: "pvp", icon: SwordIcon, type: "boolean", category: "gameplay"},
    {name: "force-gamemode", icon: GameControllerIcon, type: "boolean", category: "gameplay"},
    {name: "allow-flight", icon: PlayIcon, type: "boolean", category: "gameplay"},
    {name: "enable-command-block", icon: CommandIcon, type: "boolean", category: "gameplay"},

    {name: "level-name", icon: DatabaseIcon, type: "string", category: "world"},
    {name: "level-seed", icon: GlobeHemisphereWestIcon, type: "string", category: "world"},
    {name: "generate-structures", icon: CubeIcon, type: "boolean", category: "world"},
    {name: "spawn-protection", icon: ShieldIcon, type: "number", category: "world"},
    {name: "allow-nether", icon: GlobeHemisphereWestIcon, type: "boolean", category: "world"},
    {name: "generator-settings", icon: FileCodeIcon, type: "json", category: "world"},

    {name: "spawn-npcs", icon: UserIcon, type: "boolean", category: "spawning"},
    {name: "spawn-animals", icon: UsersIcon, type: "boolean", category: "spawning"},
    {name: "spawn-monsters", icon: WarningIcon, type: "boolean", category: "spawning"},
    
    {name: "max-players", icon: UsersIcon, type: "number", category: "players"},
    {name: "player-idle-timeout", icon: TimerIcon, type: "number", category: "players"},
    {name: "hide-online-players", icon: UsersIcon, type: "boolean", category: "players"},
    {name: "op-permission-level", icon: ShieldIcon, type: "number", category: "players"},

    {name: "server-port", icon: GlobeIcon, type: "number", category: "network"},
    {name: "online-mode", icon: LockKeyIcon, type: "boolean", category: "network"},
    {name: "network-compression-threshold", icon: WifiHighIcon, type: "number", category: "network"},
    {name: "prevent-proxy-connections", icon: WifiHighIcon, type: "boolean", category: "network"},
    {name: "use-native-transport", icon: WifiHighIcon, type: "boolean", category: "network"},
    {name: "accepts-transfers", icon: WifiHighIcon, type: "boolean", category: "network"},
    {name: "rate-limit", icon: WifiHighIcon, type: "number", category: "network"},
    {name: "log-ips", icon: WifiHighIcon, type: "boolean", category: "network"},

    {name: "view-distance", icon: EyeIcon, type: "number", category: "performance"},
    {name: "simulation-distance", icon: LayoutIcon, type: "number", category: "performance"},
    {name: "max-tick-time", icon: TimerIcon, type: "number", category: "performance"},
    {name: "max-chained-neighbor-updates", icon: WifiHighIcon, type: "number", category: "performance"},
    {name: "sync-chunk-writes", icon: WifiHighIcon, type: "boolean", category: "performance"},
    {name: "pause-when-empty-seconds", icon: TimerIcon, type: "number", category: "performance"},

    {name: "white-list", icon: ListIcon, type: "boolean", category: "security"},
    {name: "enforce-whitelist", icon: ListIcon, type: "boolean", category: "security"},
    {name: "enforce-secure-profile", icon: ShieldIcon, type: "boolean", category: "security"},

    {name: "enable-rcon", icon: TerminalIcon, type: "boolean", category: "rcon"},
    {name: "rcon.port", icon: TerminalIcon, type: "number", category: "rcon"},
    {name: "rcon.password", icon: KeyIcon, type: "string", category: "rcon"},
    {name: "broadcast-rcon-to-ops", icon: WifiHighIcon, type: "boolean", category: "rcon"},
    {name: "broadcast-console-to-ops", icon: WifiHighIcon, type: "boolean", category: "rcon"},
    {name: "enable-query", icon: BroadcastIcon, type: "boolean", category: "rcon"},
    {name: "query.port", icon: BroadcastIcon, type: "number", category: "rcon"},

    {name: "resource-pack", icon: PackageIcon, type: "string", category: "resourcepack"},
    {name: "require-resource-pack", icon: PackageIcon, type: "boolean", category: "resourcepack"},

    {name: "motd", icon: ChatCircleIcon, type: "string", category: "info"},
    {name: "enable-status", icon: WifiHighIcon, type: "boolean", category: "info"},

    {name: "enable-jmx-monitoring", icon: ChartLineUpIcon, type: "boolean", category: "advanced"},
    {name: "debug", icon: TerminalIcon, type: "boolean", category: "advanced"},
    {name: "snooper-enabled", icon: WifiHighIcon, type: "boolean", category: "advanced"},
];