name: VoxelDash
version: ${project.version}
main: de.gnm.voxeldash.VoxelDashSpigot
api-version: '1.21'
description: A web-based dashboard for managing your Minecraft server
author: GNM
website: https://voxeldash.dev/
load: STARTUP

commands: {}

permissions: {}
